import argparse
import json
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parent
MISSION_EXE = Path("D:/AFsim/AFSim/afsim-2.9.0-win64/bin/mission.exe")


REQUIRED_TOP_LEVEL_FIELDS = [
    "name",
    "includes",
    "event_pipe",
    "event_output",
    "end_time",
]


def load_scenario(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def validate_scenario(data: dict) -> list[str]:
    errors = []
    for field in REQUIRED_TOP_LEVEL_FIELDS:
        if field not in data:
            errors.append(f"Missing required field: {field}")

    includes = data.get("includes", [])
    if not isinstance(includes, list) or not includes:
        errors.append("includes must be a non-empty list")
    else:
        for include_path in includes:
            if not Path(include_path).exists():
                errors.append(f"include file does not exist: {include_path}")

    event_pipe = data.get("event_pipe", {})
    if not event_pipe.get("file"):
        errors.append("event_pipe.file is required")

    event_output = data.get("event_output", {})
    if not event_output.get("file"):
        errors.append("event_output.file is required")
    if not isinstance(event_output.get("enabled_events", []), list):
        errors.append("event_output.enabled_events must be a list")

    end_time = data.get("end_time", {})
    if not isinstance(end_time.get("value"), int):
        errors.append("end_time.value must be an integer")
    if end_time.get("unit") not in {"sec", "min", "hr"}:
        errors.append("end_time.unit must be one of: sec, min, hr")

    return errors


def render_afsim_main(data: dict) -> str:
    lines = [
        "# Generated by afsim_ai.py from structured JSON.",
        "# First learning MVP: JSON -> AFSIM main scenario script.",
        "",
    ]

    for include_path in data["includes"]:
        lines.append(f"include {include_path}")

    lines.extend(
        [
            "",
            "event_pipe",
            f"   file {data['event_pipe']['file']}",
            "end_event_pipe",
            "",
            "event_output",
            f"   file {data['event_output']['file']}",
        ]
    )

    for event_name in data["event_output"].get("enabled_events", []):
        lines.append(f"   enable {event_name}")

    lines.extend(
        [
            "end_event_output",
            "",
            f"end_time {data['end_time']['value']} {data['end_time']['unit']}",
            "",
        ]
    )
    return "\n".join(lines)


def command_validate(args: argparse.Namespace) -> int:
    data = load_scenario(Path(args.scenario_json))
    errors = validate_scenario(data)
    if errors:
        print("Validation failed:")
        for error in errors:
            print(f"  - {error}")
        return 1
    print("Validation passed.")
    return 0


def command_generate(args: argparse.Namespace) -> int:
    data = load_scenario(Path(args.scenario_json))
    errors = validate_scenario(data)
    if errors:
        print("Cannot generate because validation failed:")
        for error in errors:
            print(f"  - {error}")
        return 1

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_afsim_main(data), encoding="utf-8")
    print(f"Generated: {output_path}")
    return 0


def command_run(args: argparse.Namespace) -> int:
    scenario_path = Path(args.afsim_txt).resolve()
    if not scenario_path.exists():
        print(f"AFSIM scenario file does not exist: {scenario_path}")
        return 1
    if not MISSION_EXE.exists():
        print(f"mission.exe not found: {MISSION_EXE}")
        return 1

    scenario_path.parent.joinpath("output").mkdir(parents=True, exist_ok=True)
    result = subprocess.run(
        [str(MISSION_EXE), str(scenario_path)],
        cwd=str(scenario_path.parent),
        text=True,
        capture_output=True,
        check=False,
    )
    print(result.stdout)
    if result.stderr:
        print(result.stderr)
    print(f"mission.exe exit code: {result.returncode}")
    return result.returncode


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Learning MVP for AFSIM intelligent scenario generation."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    validate_parser = subparsers.add_parser("validate")
    validate_parser.add_argument("scenario_json")
    validate_parser.set_defaults(func=command_validate)

    generate_parser = subparsers.add_parser("generate")
    generate_parser.add_argument("scenario_json")
    generate_parser.add_argument(
        "--output",
        default=str(ROOT / "build" / "eoir_demo_generated.txt"),
    )
    generate_parser.set_defaults(func=command_generate)

    run_parser = subparsers.add_parser("run")
    run_parser.add_argument("afsim_txt")
    run_parser.set_defaults(func=command_run)

    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
