import argparse
import json
import re
import shutil
import subprocess
import urllib.request
from datetime import datetime
from pathlib import Path

import afsim_ai


ROOT = Path(__file__).resolve().parent
KNOWLEDGE = ROOT / "knowledge"
PROMPTS = ROOT / "prompts"
BUILD = ROOT / "build"
EXAMPLES = ROOT / "examples"
DEFAULT_ENDPOINT = "http://127.0.0.1:11434/api/generate"
DEFAULT_MODEL = "qwen2.5:0.5b"


def load_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def write_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def load_json(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def tokenize(text: str) -> set[str]:
    words = set(re.findall(r"[A-Za-z0-9_]+", text.lower()))
    for keyword in ["eoir", "sensor", "event", "target", "uav", "route", "imaging"]:
        if keyword in text.lower():
            words.add(keyword)
    return words


def retrieve_knowledge(request_text: str, top_k: int = 3) -> list[dict]:
    request_terms = tokenize(request_text)
    hits = []
    for path in KNOWLEDGE.rglob("*.md"):
        text = load_text(path)
        terms = tokenize(text)
        score = len(request_terms & terms)
        if score:
            hits.append({"path": str(path.relative_to(ROOT)), "score": score, "text": text})
    hits.sort(key=lambda item: (-item["score"], item["path"]))
    return hits[:top_k]


def format_context(hits: list[dict]) -> str:
    blocks = []
    for hit in hits:
        blocks.append(f"## {hit['path']} (score={hit['score']})\n\n{hit['text'].strip()}")
    return "\n\n---\n\n".join(blocks)


def extract_json(text: str) -> dict:
    text = text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?", "", text, flags=re.IGNORECASE).strip()
        text = re.sub(r"```$", "", text).strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        start = text.find("{")
        end = text.rfind("}")
        if start >= 0 and end > start:
            return json.loads(text[start : end + 1])
        raise


def call_ollama(prompt: str, model: str, endpoint: str) -> dict:
    payload = {
        "model": model,
        "stream": False,
        "format": "json",
        "options": {"temperature": 0.1, "top_p": 0.9},
        "prompt": prompt,
    }
    request = urllib.request.Request(
        endpoint,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    opener = urllib.request.build_opener(urllib.request.ProxyHandler({}))
    with opener.open(request, timeout=180) as response:
        body = json.loads(response.read().decode("utf-8"))
    return extract_json(body.get("response", ""))


def rule_fallback() -> dict:
    draft = afsim_ai.local_rule_draft()
    draft["name"] = "eoir_agent_loop_demo"
    draft["description"] = "Generated by the step 07 agent rule fallback."
    draft["event_pipe"]["file"] = "output/eoir_agent_loop_demo.aer"
    draft["event_output"]["file"] = "output/eoir_agent_loop_demo.evt"
    return draft


class AgentTrace:
    def __init__(self) -> None:
        self.events = []

    def add(self, step: str, status: str, detail: str, data: dict | None = None) -> None:
        self.events.append(
            {
                "time": datetime.now().isoformat(timespec="seconds"),
                "step": step,
                "status": status,
                "detail": detail,
                "data": data or {},
            }
        )

    def save(self, path: Path) -> None:
        write_json(path, {"events": self.events})


def build_draft_prompt(request_text: str, context: str) -> str:
    return (
        f"{load_text(PROMPTS / 'agent_draft_prompt.md')}\n\n"
        f"## 检索到的 AFSIM 知识\n\n{context}\n\n"
        f"## 用户需求\n\n{request_text}\n"
    )


def build_repair_prompt(request_text: str, context: str, draft: dict, errors: list[str]) -> str:
    return (
        f"{load_text(PROMPTS / 'agent_repair_prompt.md')}\n\n"
        f"## 用户需求\n\n{request_text}\n\n"
        f"## 检索到的 AFSIM 知识\n\n{context}\n\n"
        f"## 当前 JSON\n\n{json.dumps(draft, ensure_ascii=False, indent=2)}\n\n"
        f"## 校验错误\n\n{json.dumps(errors, ensure_ascii=False, indent=2)}\n"
    )


def draft_with_agent(request_text: str, context: str, model: str, endpoint: str, fallback_rules: bool, trace: AgentTrace) -> dict:
    try:
        draft = call_ollama(build_draft_prompt(request_text, context), model, endpoint)
        draft["draft_provider"] = "ollama"
        trace.add("draft", "ok", "local model produced initial scenario JSON", {"model": model})
        return draft
    except Exception as exc:
        trace.add("draft", "failed", str(exc), {"model": model})
        if not fallback_rules:
            raise
        draft = rule_fallback()
        draft["draft_provider"] = "rules_fallback"
        draft["local_model_error"] = str(exc)
        trace.add("draft", "fallback", "used rule fallback scenario JSON")
        return draft


def repair_until_valid(
    request_text: str,
    context: str,
    draft: dict,
    model: str,
    endpoint: str,
    max_repairs: int,
    fallback_rules: bool,
    trace: AgentTrace,
) -> tuple[dict, list[str]]:
    for attempt in range(max_repairs + 1):
        errors = afsim_ai.validate_scenario(draft)
        if not errors:
            trace.add("validate", "ok", f"scenario JSON passed validation on attempt {attempt}")
            return draft, []
        trace.add("validate", "failed", f"validation failed on attempt {attempt}", {"errors": errors})
        if attempt >= max_repairs:
            break
        try:
            draft = call_ollama(build_repair_prompt(request_text, context, draft, errors), model, endpoint)
            draft["draft_provider"] = "ollama_repair"
            trace.add("repair", "ok", f"local model repaired scenario JSON on attempt {attempt + 1}")
        except Exception as exc:
            trace.add("repair", "failed", str(exc))
            break
    if fallback_rules:
        draft = rule_fallback()
        draft["draft_provider"] = "rules_fallback_after_repair"
        errors = afsim_ai.validate_scenario(draft)
        trace.add("repair", "fallback", "used rule fallback after repair loop", {"errors": errors})
        return draft, errors
    return draft, afsim_ai.validate_scenario(draft)


def generate_outputs(draft: dict, build_dir: Path, trace: AgentTrace) -> tuple[Path, Path]:
    errors = afsim_ai.validate_scenario(draft)
    if errors:
        raise ValueError(f"Cannot generate invalid scenario: {errors}")
    platform_types = afsim_ai.load_platform_types(draft)
    platforms = afsim_ai.expand_platforms(draft, platform_types)
    build_dir.mkdir(parents=True, exist_ok=True)
    scenario_path = build_dir / "scenario_generated.txt"
    main_path = build_dir / "main_generated.txt"
    write_text(scenario_path, afsim_ai.render_scenario_instances(platforms))
    write_text(main_path, afsim_ai.render_main(draft, platform_types, scenario_path.name))
    trace.add("generate", "ok", "generated AFSIM main and scenario files", {"platforms": len(platforms)})
    return main_path, scenario_path


def run_mission(main_path: Path, trace: AgentTrace) -> int:
    main_path = main_path.resolve()
    main_path.parent.joinpath("output").mkdir(parents=True, exist_ok=True)
    result = subprocess.run(
        [str(afsim_ai.MISSION_EXE), str(main_path)],
        cwd=str(main_path.parent),
        text=True,
        capture_output=True,
        check=False,
    )
    write_text(main_path.parent / "mission_stdout.log", result.stdout)
    write_text(main_path.parent / "mission_stderr.log", result.stderr)
    trace.add("run", "ok" if result.returncode == 0 else "failed", "mission.exe finished", {"exit_code": result.returncode})
    return result.returncode


def command_agent(args: argparse.Namespace) -> int:
    BUILD.mkdir(parents=True, exist_ok=True)
    trace = AgentTrace()
    request_text = load_text(Path(args.request))
    trace.add("plan", "ok", "plan: retrieve knowledge, draft JSON, validate, repair if needed, generate AFSIM, run mission")

    hits = retrieve_knowledge(request_text, args.top_k)
    context = format_context(hits)
    write_text(BUILD / "retrieval_context.md", context)
    trace.add("retrieve", "ok", "retrieved local AFSIM knowledge snippets", {"hits": [{"path": h["path"], "score": h["score"]} for h in hits]})

    try:
        draft = draft_with_agent(request_text, context, args.model, args.endpoint, args.fallback_rules, trace)
        draft, errors = repair_until_valid(
            request_text,
            context,
            draft,
            args.model,
            args.endpoint,
            args.max_repairs,
            args.fallback_rules,
            trace,
        )
        write_json(EXAMPLES / "agent_generated_scenario.json", draft)
        if errors:
            print("Agent failed to produce a valid scenario:")
            for error in errors:
                print(f"  - {error}")
            trace.save(BUILD / "agent_trace.json")
            return 1
        main_path, _ = generate_outputs(draft, BUILD, trace)
        exit_code = run_mission(main_path, trace) if args.run else 0
        trace.save(BUILD / "agent_trace.json")
        print(f"Agent trace: {BUILD / 'agent_trace.json'}")
        print(f"Retrieval context: {BUILD / 'retrieval_context.md'}")
        print(f"Scenario JSON: {EXAMPLES / 'agent_generated_scenario.json'}")
        print(f"AFSIM main: {BUILD / 'main_generated.txt'}")
        if args.run:
            print(f"mission.exe exit code: {exit_code}")
        return exit_code
    except Exception as exc:
        trace.add("agent", "failed", str(exc))
        trace.save(BUILD / "agent_trace.json")
        print(f"Agent failed: {exc}")
        return 1


def command_clean(_: argparse.Namespace) -> int:
    for path in [BUILD, EXAMPLES / "agent_generated_scenario.json"]:
        if path.is_dir():
            shutil.rmtree(path)
        elif path.exists():
            path.unlink()
    print("Cleaned step 07 generated artifacts.")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Step 07: Agent loop for local AFSIM scenario generation.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    agent_parser = subparsers.add_parser("agent")
    agent_parser.add_argument("request")
    agent_parser.add_argument("--model", default=DEFAULT_MODEL)
    agent_parser.add_argument("--endpoint", default=DEFAULT_ENDPOINT)
    agent_parser.add_argument("--top-k", type=int, default=3)
    agent_parser.add_argument("--max-repairs", type=int, default=2)
    agent_parser.add_argument("--fallback-rules", action="store_true")
    agent_parser.add_argument("--run", action="store_true")
    agent_parser.set_defaults(func=command_agent)

    clean_parser = subparsers.add_parser("clean")
    clean_parser.set_defaults(func=command_clean)
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
